repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: Run Pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff-format
        name: Run Ruff for formatting
        entry: ruff format .
        language: system
        pass_filenames: false
        always_run: true