[project]
name = "labarchives_api"
version = "0.1.0"
description = "A Python wrapper for the LabArchives ELN API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.3",
]

[dependency-groups]
test = [
    "pytest>=8.3.5",
]
dev = [
    "ruff>=0.11.11",
    "types-requests>=2.32.0.20250515",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
