[project]
name = "labarchives_api"
version = "0.1.0"
description = "A Python wrapper for the LabArchives ELN API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.3",
]

[dependency-groups]
test = [
    "pytest>=8.3.5",
]
