name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/project/labapi/

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Build distributions
        run: uv build --python 3.13 --clear --no-build-logs

      - name: Publish to TestPyPI
        run: uv publish --trusted-publishing always --check-url https://test.pypi.org/simple/ --publish-url https://test.pypi.org/legacy/
