name: Type Check

on:
  push:
  pull_request:

jobs:
  pyright:
    uses: ./.github/workflows/python_check.yml
    with:
      job_name: Pyright
      command: uv run pyright

  ty:
    uses: ./.github/workflows/python_check.yml
    with:
      job_name: ty
      command: uv run ty check
      append_python_version_arg: true
