name: Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-tests:
    uses: ./.github/workflows/python_check.yml
    with:
      job_name: Unit tests
      command: uv run pytest
